// Sample data for families with all tab content

export const sampleFamily = {
  id: 1,
  name: "Doe Family",
  members: 4,
  parents: 2,
  kids: 2,
  status: "active",
  createdDate: "2025-01-15",
  lastActivity: "2025-12-15",
  membersList: [
    { id: 1, name: "John Doe", role: "Parent", email: "john@example.com" },
    { id: 2, name: "Jane Doe", role: "Parent", email: "jane@example.com" },
    { id: 3, name: "Emma Doe", role: "Kid", email: "emma@example.com" },
    { id: 4, name: "Mike Doe", role: "Kid", email: "mike@example.com" },
  ],
  events: [
    {
      id: 1,
      title: "Family Movie Night",
      description: "Watch a family-friendly movie together",
      date: "2025-12-20",
      time: "19:00",
      location: "Living Room",
      createdBy: { id: 1, name: "John Doe" },
      createdAt: "2025-12-10T10:00:00Z",
    },
    {
      id: 2,
      title: "Weekend Picnic",
      description: "Picnic at the park",
      date: "2025-12-22",
      time: "12:00",
      location: "Central Park",
      createdBy: { id: 2, name: "Jane Doe" },
      createdAt: "2025-12-11T14:30:00Z",
    },
    {
      id: 3,
      title: "Birthday Party",
      description: "Emma's birthday celebration",
      date: "2025-12-25",
      time: "15:00",
      location: "Home",
      createdBy: { id: 1, name: "John Doe" },
      createdAt: "2025-12-12T09:00:00Z",
    },
    {
      id: 4,
      title: "Morning Walk",
      description: "Family morning walk",
      date: "2025-12-03",
      time: "08:00",
      location: "Neighborhood Park",
      createdBy: { id: 2, name: "Jane Doe" },
      createdAt: "2025-12-02T18:00:00Z",
    },
    {
      id: 5,
      title: "Dinner Out",
      description: "Family dinner at restaurant",
      date: "2025-12-15",
      time: "18:30",
      location: "Italian Restaurant",
      createdBy: { id: 1, name: "John Doe" },
      createdAt: "2025-12-14T10:00:00Z",
    },
  ],
  meals: [
    {
      id: 1,
      name: "Breakfast",
      date: "2025-12-15",
      time: "08:00",
      type: "breakfast",
      description: "Pancakes and eggs",
      createdBy: { id: 2, name: "Jane Doe" },
      createdAt: "2025-12-14T20:00:00Z",
    },
    {
      id: 2,
      name: "Dinner",
      date: "2025-12-15",
      time: "18:00",
      type: "dinner",
      description: "Pasta with meatballs",
      createdBy: { id: 1, name: "John Doe" },
      createdAt: "2025-12-15T12:00:00Z",
    },
    {
      id: 3,
      name: "Lunch",
      date: "2025-12-16",
      time: "12:30",
      type: "lunch",
      description: "Sandwiches and salad",
      createdBy: { id: 2, name: "Jane Doe" },
      createdAt: "2025-12-15T19:00:00Z",
    },
  ],
  lists: [
    {
      id: 1,
      title: "Grocery Shopping",
      items: [
        { id: 1, name: "Milk", completed: false },
        { id: 2, name: "Bread", completed: true },
        { id: 3, name: "Eggs", completed: false },
      ],
      createdBy: { id: 2, name: "Jane Doe" },
      createdAt: "2025-12-14T10:00:00Z",
    },
    {
      id: 2,
      title: "Weekend Activities",
      items: [
        { id: 1, name: "Visit museum", completed: false },
        { id: 2, name: "Play soccer", completed: false },
      ],
      createdBy: { id: 1, name: "John Doe" },
      createdAt: "2025-12-13T15:00:00Z",
    },
  ],
  media: {
    folders: [
      {
        id: 1,
        name: "Trip to Beach",
        imageCount: 15,
        thumbnail: "/api/placeholder/150/150",
        createdAt: "2025-12-01",
        createdBy: { id: 1, name: "John Doe" },
      },
      {
        id: 2,
        name: "Birthday Party",
        imageCount: 8,
        thumbnail: "/api/placeholder/150/150",
        createdAt: "2025-11-20",
        createdBy: { id: 2, name: "Jane Doe" },
      },
    ],
    images: [
      {
        id: 1,
        name: "family-photo.jpg",
        url: "/api/placeholder/300/300",
        size: "2.5 MB",
        uploadedBy: { id: 1, name: "John Doe" },
        uploadedAt: "2025-12-10T10:00:00Z",
      },
      {
        id: 2,
        name: "vacation.jpg",
        url: "/api/placeholder/300/300",
        size: "1.8 MB",
        uploadedBy: { id: 2, name: "Jane Doe" },
        uploadedAt: "2025-12-08T14:00:00Z",
      },
    ],
  },
  tracker: [
    {
      id: 1,
      type: "location",
      title: "Family Location",
      description: "Real-time family member locations",
      lastUpdate: "2025-12-15T18:30:00Z",
      status: "active",
    },
    {
      id: 2,
      type: "expense",
      title: "Monthly Expenses",
      description: "Track family expenses",
      lastUpdate: "2025-12-15T12:00:00Z",
      status: "active",
    },
  ],
  recipes: [
    {
      id: 1,
      name: "Grandma's Chocolate Chip Cookies",
      category: "dessert",
      prepTime: "15 min",
      cookTime: "12 min",
      servings: 24,
      ingredients: [
        "2 1/4 cups all-purpose flour",
        "1 tsp baking soda",
        "1 cup butter, softened",
        "3/4 cup granulated sugar",
        "3/4 cup brown sugar",
        "2 large eggs",
        "2 cups chocolate chips",
      ],
      instructions: [
        "Preheat oven to 375°F",
        "Mix flour and baking soda in a bowl",
        "Cream butter and sugars, then add eggs",
        "Gradually blend in flour mixture",
        "Stir in chocolate chips",
        "Drop rounded tablespoons onto ungreased cookie sheets",
        "Bake for 9-11 minutes until golden brown",
      ],
      createdBy: { id: 2, name: "Jane Doe" },
      createdAt: "2025-12-10T10:00:00Z",
    },
    {
      id: 2,
      name: "Homemade Pasta Sauce",
      category: "main course",
      prepTime: "10 min",
      cookTime: "45 min",
      servings: 6,
      ingredients: [
        "2 tbsp olive oil",
        "1 onion, diced",
        "3 cloves garlic, minced",
        "28 oz crushed tomatoes",
        "1 tsp dried basil",
        "1 tsp dried oregano",
        "Salt and pepper to taste",
      ],
      instructions: [
        "Heat olive oil in a large pan",
        "Sauté onion until translucent",
        "Add garlic and cook for 1 minute",
        "Add crushed tomatoes and spices",
        "Simmer for 30-40 minutes",
        "Season with salt and pepper",
      ],
      createdBy: { id: 1, name: "John Doe" },
      createdAt: "2025-12-08T14:00:00Z",
    },
    {
      id: 3,
      name: "Healthy Green Smoothie",
      category: "beverage",
      prepTime: "5 min",
      cookTime: "0 min",
      servings: 2,
      ingredients: [
        "2 cups spinach",
        "1 banana",
        "1 cup almond milk",
        "1/2 cup frozen mango",
        "1 tbsp honey",
      ],
      instructions: [
        "Add all ingredients to a blender",
        "Blend until smooth",
        "Serve immediately",
      ],
      createdBy: { id: 2, name: "Jane Doe" },
      createdAt: "2025-12-05T08:00:00Z",
    },
  ],
};

